version: "3.9"
services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: dockerfile-frontend
    ports:
      - "8000:8000"
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: dockerfile-backend
    network_mode: host


