FROM ubuntu:20.04
ENV TZ=Europe/Moscow

RUN mkdir web
WORKDIR ./web

RUN mkdir ./src/ && mkdir ./src/main/ && mkdir ./src/main/resources/ && mkdir ./src/main/java/ && mkdir ./src/main/resources/templates

COPY /src/main/java ./src/main/java
COPY /src/main/resources/templates ./src/main/resources/templates
COPY pom.xml .
COPY /src/main/resources/application.properties ./src/main/resources

RUN apt-get update
RUN apt-get install default-jdk -y
RUN apt-get install maven -y

RUN mvn clean package

CMD ["java","-jar","./target/Games-0.0.1-SNAPSHOT.jar"]