name: Test App
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Postgres
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: kirill
          password: 123
          database: games
          port: 5432
        id: postgres

      - name: psycopg2
        run: sudo apt install python3-pip -y && pip install psycopg2

      - name: Setup database
        run: python3 db.py




