name: Test App
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Postgres
        uses: ikalnytskyi/action-setup-postgres@v4
        with:
          username: kirill
          password: 123
          database: games
          port: 5432
        id: postgres

      - name: psycopg2
        run: sudo apt install python3-pip -y && pip install psycopg2

      - name: Setup Database
        run: python3 db.py

      - name: Build App
        run: docker-compose up -d

      - name: Auth
        run: curl -i -H "Content-type':' application/x-www-form-urlencoded" --cookie coockies.txt --cookie-jar newcookies.txt -d login=john -d password=123 -L http://localhost':'8080/login

      - name: Test Auth
        run: curl --cookie newcookies.txt   http://localhost':'8080/api/player/authenticated >> data.txt && cat data.txt





